echo -e ".. This file is auto-generated by Makefile\n\tDO NOT EDIT\n\n" >index.rst
for i in "$(find notes/ -mindepth 1 -maxdepth 1 -type d | sort)"; do
  echo "Scanning directory $i"
  echo -e "<!--This file is auto-generated by Makefile\n----DO NOT EDIT -->" >"$i".md
  # To set name in toctree use :caption:
  echo -e ".. toctree::\n\t:maxdepth: 3\n\n\tassets/$i.md\n" >>index.rst
  for j in "$(find "$i" -type f -name \\*md | sort)"; do
    echo "$j"
    echo -e "---\n_Notatki z pliku \`$j\`_" >>"$i".md
    echo -e "\`\`\`{include} ../$j\n\`\`\`" >>"$i".md
  done
done
